### ISSUE TITLE
configurable chance for dropping?

### ISSUE THREAD

**Issue by kuba26038** [matthewperiut/birdnest#1]
i think that the nests are a little bit too common, i found 8 in a single azalea tree for example. i don't know what the current chance is, but it feels like it's way too much. so, i'd like for the chance to be configurable, is that possible?

**Comment by matthewperiut** [comment]
SIGH yea youre right, im gonna make it 10x less likely and add a config

**Comment by kuba26038** [comment]
cool to see the newest version have the config, but... why the mod called "chisel" after i download it?

**Comment by matthewperiut** [comment]
mistake will fix

**Comment by kuba26038** [comment]
additionally, the config doesn't have any comments that explain what it does. i assume that the only value that is there is the value by which the chance is divided, since when i increased it, the chance was reduced, i expected it to be something like a percentage, though, that's why i increased it in the first place. something like "the chance for any leaf block to drop a bird's nest is 100% divided by this value".

**Comment by matthewperiut** [comment]
Very true, but on the mod's page at the bottom it explains the config as the number of leaves to break to get one birdnest on average

**Comment by kuba26038** [comment]
just now i broke like 12 normal trees and haven't gotten a single nest; i think either something broke when i set the value to 100, or i got insanely unlucky and  idk which it is but i assume you do know?

**Comment by matthewperiut** [comment]
oh gosh i tested it and thought it was weird it took forever to get one too lol, ill look into it sorry about that

**Comment by matthewperiut** [comment]
works as expected, it drops a little less commonly than apples, and i think thats fair, i wanted it drastically less likely because you can literally get diamonds
