### ISSUE TITLE
Wrong mod uploaded

### ISSUE THREAD

**Issue by Iggoreum** [matthewperiut/birdnest#2]
It seems you've uploaded chisel into modrinth, instead of birdnest, in the birdnest mod page. Either that or the name is different.

**Comment by matthewperiut** [comment]
i'll check it out thanks geez

**Comment by matthewperiut** [comment]
wait which one i dont see what you mean

**Comment by matthewperiut** [comment]
LOL wait the name is just wrong thats my bad

**Comment by Iggoreum** [comment]
Oh lol, happens to the best of us. Thanks for quick reply!
