### ISSUE TITLE
Nests not dropping from leaves in 1.21.1

### ISSUE THREAD

**Issue by vico93** [matthewperiut/birdnest#3]
Just tried your fork on 1.21.1, seems like it isnt dropping from leaves when breaking trees - default config, while in 1.21.3 with the default too it drops normally.

Didn't find anything related to birdnest on `latest.log`, unfortunately.

**Comment by matthewperiut** [comment]
I must've already fixed this, I just tested latest on 1.21.1 fork, works as expected.
